title: Update notification setting params
type: object
properties:
  why_is_it_moving_enabled:
    type: boolean
    description: Price movement enabled
  statistic_52_weeks_enabled:
    type: boolean
    description: Price movement enabled
  price_movement_threshold:
    type: number
    description: Value of threshold
  corporate_actions_enabled:
    type: boolean
    description: Corporate actions enabled
  breaking_news_enabled:
    type: boolean
    description: Breaking news enabled
